services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: football_league
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    # mappage pour éviter un conflit avec une instance postgres locale
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:password@db:5432/football_league
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  db_data:
